# Generated by Django 4.1 on 2022-08-18 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_api', '0005_alter_despesa_valor_alter_receita_descricao_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='despesa',
            name='descricao_unica_por_mes',
        ),
        migrations.AddField(
            model_name='despesa',
            name='categoria',
            field=models.CharField(choices=[('alimentacao', 'Alimentação'), ('saude', 'Saúde'), ('moradia', 'Moradia'), ('transporte', 'Transporte'), ('educacao', 'Educaçao'), ('lazer', 'Lazer'), ('imprevistos', 'Imprevistos'), ('outros', 'Outros')], default='outros', max_length=11),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='descricao',
            field=models.CharField(max_length=255, unique_for_month='data'),
        ),
    ]
