# Generated by Django 4.1 on 2022-08-29 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_api', '0009_alter_despesa_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesa',
            name='descricao',
            field=models.CharField(max_length=255),
        ),
    ]
